// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPRDDaKlDhWA_i24OJ1g9LhqeT3b9o0c',
    appId: '1:818590629112:android:fd3d83bd78a323743c0f0d',
    messagingSenderId: '818590629112',
    projectId: 'beezbug-448dc',
    storageBucket: 'beezbug-448dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBf0dsYOyTy7ECmrbvGo3V8C5hJ2G8Ex4',
    appId: '1:818590629112:ios:d380c66942f447183c0f0d',
    messagingSenderId: '818590629112',
    projectId: 'beezbug-448dc',
    storageBucket: 'beezbug-448dc.appspot.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBf0dsYOyTy7ECmrbvGo3V8C5hJ2G8Ex4',
    appId: '1:818590629112:ios:d380c66942f447183c0f0d',
    messagingSenderId: '818590629112',
    projectId: 'beezbug-448dc',
    storageBucket: 'beezbug-448dc.appspot.com',
    iosBundleId: 'com.example.ecom',
  );
}
